version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  bimserver:  
    build:
      context: .
      args:
        BIMSERVER_VERSION: ${BIMSERVER_VERSION}
    image: bimserver:${BIMSERVER_VERSION}
    hostname: bimserver
    logging: *default-logging
    networks:
      - frontend
    volumes:
      - bimdata:/var/bimserver
    ports:
      - 8080
    environment:
      CATALINA_OPTS: "-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      TOMCAT_USER: ${TOMCAT_USER}
      TOMCAT_PASSWORD: ${TOMCAT_PASSWORD}
    labels:
      - "traefik.docker.network=frontend"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:bim.traefik.local"

networks:
  frontend:
    external: true

volumes:
  bimdata:
